default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: furima_41639_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: furima_41639_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>